### ISSUE TITLE
Add Support for hours/minutes/seconds

### ISSUE THREAD

**Issue by boazarad** [boazarad/MMM-CountDown#1]
TODO: Add option to display a more detailed countdown with Hours, Minutes and/or seconds.

**Comment by nawak86** [comment]
Hello can you add french translation with option :
lang: fr, ??

days=jours

thank you for your work

**Comment by maartenpaauw** [comment]
> Hello can you add french translation with option :
> lang: fr, ??
> 
> days=jours
> 
> thank you for your work

I've created this module translatable. Feel free to make a pull request with the right translation inside the `translations` folder saved as `fr.json`.
