### ISSUE TITLE
Keep getting update notification.

### ISSUE THREAD

**Issue by aunrea** [boazarad/MMM-CountDown#11]
I keep getting the message:

> Update available for MMM-CountDown module.
The current installation is 5 commits behind on the master branch.

I tried to update the module but it keeps saying it is already up to date.

**Comment by boazarad** [comment]
Have you tried rebooting your system?
Could you explain exactly how you're attempting to update the module?

**Comment by aunrea** [comment]
I have rebooted several times. I did a git pull to update it.
