### ISSUE TITLE
Let the countdown be a date/time, not just date.

### ISSUE THREAD

**Issue by rossburton** [boazarad/MMM-CountDown#7]

**Comment by tim-digitised** [comment]
Hey mate, I was the one who committed the code changes to support the date/time and additional labels, and you're right, I did not specifically say it supports date/time, there are configurable parameters that lets these be set. 

I'm working on an update to this module, I'll apply your suggestions to it and submit a PR to @boazarad

**Comment by boazarad** [comment]
Addressed in precious update, thanks @tim-digitised !
